### ISSUE TITLE
Data loss with hyperref (\hyperindexformat)

### ISSUE THREAD

**Issue by creidieki** [debian-tex/xindy#4]
When using xindy with the hyperref package, "see also" entries aren't printed in the output.

A minimum test case is presented in a stackoverflow question (https://tex.stackexchange.com/questions/586354/  ) but the bug has been reported since 2009 (https://sourceforge.net/p/xindy/bugs/62/  ) . There's a pull request at https://github.com/jschrod/xindy.ctan/pull/6   that's been up since 2019 but hasn't been merged. xindy doesn't seem to be actively maintained; would there be any chance of getting that pull request merged in the Debian packaging?

**Comment by norbusan** [comment]
Hi @creidieki 
thanks for point me at this.
I will surely include this in the Debian packages, but I guess it is too late for bullseye ...
Concerning further changes, I am in discussion with TeX Live upstream on how we can get fixes for xindy included.
Thanks a lot
Norbert

**Comment by norbusan** [comment]
Just uploaded a version with the patch included.

**Comment by creidieki** [comment]
Thank you so much for looking at this promptly!! I know it may be a while before we see it, but I really appreciate you looking at this.
